ARG node_version
FROM node:$node_version as build-step
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app
RUN npm run build-prod

FROM nginx:latest
COPY --from=build-step /app/dist/OnlinePortfolioFrontEnd /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && envsubst </usr/share/nginx/html/assets/env.template.js> /usr/share/nginx/html/assets/env.js && nginx -g 'daemon off;'